volumes:
  pgdata:
    name: esd_pgdata
  rabbitmq_data:
    name: esd_rabbitmq_data

networks:
  public-net: # Public network for Kong and Cloud CDN integration
    driver: bridge
    name: public-net
  internal-net: # Internal network for Traefik and microservices
    driver: bridge
    name: internal-net

services:
  kong:
    image: kong/kong-gateway:3.9.0.1
    container_name: kong-dbless
    restart: always
    networks:
      - public-net
      - internal-net
    volumes:
      - ./kong:/kong/declarative
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_LICENSE_DATA: ""
    ports:
      - "8000:8000" # Public API port
      - "8443:8443" # Public HTTPS API port
      - "8001:8001" # Admin API port
      - "8444:8444" # Admin HTTPS API port
      - "8002:8002" # Admin GUI port
      - "8445:8445" # Admin GUI HTTPS port
      - "8003:8003" # Additional ports if needed
      - "8004:8004"

  traefik:
    image: traefik:v2.9
    container_name: traefik-ingress
    restart: always
    networks:
      - internal-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # For dynamic service discovery
    command:
      - --api.insecure=true # Enable Traefik dashboard (for testing)
      - --providers.docker # Enable Docker provider
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "8200:8080" # GUI
      - "443:443"
      - "80:80"
    labels:
      - "traefik.http.routers.traefik.entrypoints=web"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - internal-net
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.internal`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.entrypoints=web"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - internal-net
    ports:
      - "1010:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.internal`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=web"

  complete-order:
    build: ./services/complex/complete-order
    container_name: complete-order
    networks:
      - internal-net
    ports:
      - "7070:7070"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    labels:
      - "traefik.http.routers.complete-order.rule=Host(`complete.internal`)"
      - "traefik.http.services.complete-order.loadbalancer.server.port=7070"
      - "traefik.http.routers.complete-order.entrypoints=web"

  reccomend-food:
    build: ./services/complex/reccomend-food
    container_name: reccomend-food
    networks:
      - internal-net
    ports:
      - "8080:8080"
    depends_on:
      - reccomendation
      - menu
    labels:
      - "traefik.http.routers.recommend-food.rule=Host(`recommend.internal`)"
      - "traefik.http.services.recommend-food.loadbalancer.server.port=8080"
      - "traefik.http.routers.recommend-food.entrypoints=web"

  order-food:
    build: ./services/complex/order-food
    container_name: order-food
    networks:
      - internal-net
    ports:
      - "8090:8090"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    labels:
      - "traefik.http.routers.order-food.rule=Host(`order.internal`)"
      - "traefik.http.services.order-food.loadbalancer.server.port=8090"
      - "traefik.http.routers.order-food.entrypoints=web"

  chatgpt:
    build: ./services/simple/chatgpt
    container_name: chatgpt
    networks:
      - internal-net
    ports:
      - "3000:3000"
    env_file:
      - ./services/simple/chatgpt/.env
    labels:
      - "traefik.http.routers.chatgpt.rule=Host(`chatgpt.internal`)"
      - "traefik.http.services.chatgpt.loadbalancer.server.port=3000"
      - "traefik.http.routers.chatgpt.entrypoints=web"

  menu:
    build: ./services/simple/menu
    container_name: menu
    networks:
      - internal-net
    ports:
      - "5001:5001"
    volumes:
      - ./services/simple/menu/firebase_credentials.json:/app/firebase_credentials.json
    labels:
      - "traefik.http.routers.menu.rule=Host(`menu.internal`)"
      - "traefik.http.services.menu.loadbalancer.server.port=5001"
      - "traefik.http.routers.menu.entrypoints=web"

  reccomendation:
    build: ./services/simple/reccomendation
    container_name: reccomendation
    networks:
      - internal-net
    ports:
      - "4000:4000"
    env_file:
      - ./services/simple/reccomendation/.env
    labels:
      - "traefik.http.routers.recommendation.rule=Host(`recommendation.internal`)"
      - "traefik.http.services.recommendation.loadbalancer.server.port=4000"
      - "traefik.http.routers.recommendation.entrypoints=web"

  payment:
    build: ./services/simple/payment
    container_name: payment
    networks:
      - internal-net
    ports:
      - "5002:5002"
    env_file:
      - ./services/simple/payment/.env
    labels:
      - "traefik.http.routers.payment.rule=Host(`payment.internal`)"
      - "traefik.http.services.payment.loadbalancer.server.port=5002"
      - "traefik.http.routers.payment.entrypoints=web"

  order:
    build: ./services/simple/order
    container_name: order
    networks:
      - internal-net
    ports:
      - "6369:6369"
    env_file:
      - ./services/simple/order/.env
    labels:
      - "traefik.http.routers.order.rule=Host(`order.internal`)"
      - "traefik.http.services.order"
      - "traefik.http.routers.order.entrypoints=web"

  queue:
    build: ./services/simple/queue
    container_name: queue
    networks:
      - internal-net
    ports:
      - "8008:8008"
    depends_on:
      - socketio
    env_file:
      - ./services/simple/queue/.env
    environment:
      - SOCKET_IO_URL=http://socketio:3300
    labels:
      - "traefik.http.routers.queue.rule=Host(`queue.internal`)"
      - "traefik.http.services.queue.loadbalancer.server.port=8008"
      - "traefik.http.routers.queue.entrypoints=web"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: foodapp-rabbit
    restart: always
    ports:
      - "5672:5672" # RabbitMQ Client Connection
      - "15672:15672" # RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
    labels:
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.internal`)"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.http.routers.rabbitmq.entrypoints=web"

  rabbitmq-setup:
    build: ./rabbitmq-setup
    container_name: amqp-setup
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - internal-net
    labels:
      - traefik.enable=false

  socketio:
    build: ./socket.io
    container_name: socket.io
    networks:
      - internal-net
    ports:
      - "3300:3300"
    depends_on:
      rabbitmq:
        condition: service_started # Checks if service started + running properly
      rabbitmq-setup:
        condition: service_completed_successfully #check if service has completed
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672 #connect to rabbitmq at port 5762 with the cred of username: guest and password: guest
      - KONG_URL=http://kong:8000
    labels:
      - "traefik.http.routers.socketio.rule=Host(`socketio.internal`)"
      - "traefik.http.services.socketio.loadbalancer.server.port=3300"
      - "traefik.http.routers.socketio.entrypoints=web"

# not longer necessary
#   credit:
#     build: ./services/simple/credit
#     container_name: credit
#     networks:
#       - esd-net
#     ports:
#       - "4040:4040"
#     env_file:
#       - ./services/simple/credit/.env

#   frontend:
#     build: ../frontend
#     container_name: frontend
#     ports:
#       - "3001:80"
#     networks:
#       - esd-net

