version: '3.8'

services:
  # kong:
  #   image: kong/kong-gateway:latest
  #   container_name: kong
  #   environment:
  #     KONG_DATABASE: "off"
  #     KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
  #   volumes:
  #     - ./kong/kong.yml:/etc/kong/kong.yml
  #   ports:
  #     - "8001:8000" 
  #     - "8443:8443"
  #     - "8002:8001"
  #     - "8444:8444"
  #   restart: always

  reccomend-food:
    build: ./services/complex/reccomend-food
    container_name: reccomend-food
    ports:
      - "8080:8080"
    depends_on:
      - reccomendation
      - menu
  
  chatgpt:
    build: ./services/simple/chatgpt
    container_name: chatgpt
    ports:
      - "3000:3000"
    env_file:
      - ./services/simple/chatgpt/.env

  menu:
    build: ./services/simple/menu
    container_name: menu
    ports:
      - "5001:5000"
    volumes:
      - ./services/simple/menu/firebase_credentials.json:/app/firebase_credentials.json

  reccomendation:
    build: ./services/simple/reccomendation
    container_name: reccomendation
    ports:
      - "4000:4000"
    env_file:
      - ./services/simple/reccomendation/.env
