apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt
  template:
    metadata:
      labels:
        app: chatgpt
    spec:
      containers:
      - name: chatgpt-container
        image: ghcr.io/thykp/esd_team8-chatgpt:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: chatgpt-secret
