apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt
  template:
    metadata:
      labels:
        app: chatgpt
    spec:
      containers:
      - name: chatgpt-container
        image: asia-southeast1-docker.pkg.dev/findmyfood-455107/my-repo/chatgpt:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: chatgpt-secret
