apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-order
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complete-order
  template:
    metadata:
      labels:
        app: complete-order
    spec:
      containers:
      - name: complete-order
        image: asia-southeast1-docker.pkg.dev/findmyfood-455107/my-repo/complete-order:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
