apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit
  template:
    metadata:
      labels:
        app: credit
    spec:
      containers:
      - name: credit
        image: your-registry/credit:latest
        ports:
        - containerPort: 4040
        envFrom:
        - configMapRef:
            name: credit-secret
