apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
      - name: menu
        image: your-dockerhub-username/menu:latest
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: firebase-credentials
          mountPath: /app/firebase_credentials.json
          subPath: firebase_credentials.json
      volumes:
      - name: firebase-credentials
        configMap:
          name: firebase-credentials-config
