apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: asia-southeast1-docker.pkg.dev/findmyfood-455107/my-repo/order:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6369
        envFrom:
        - secretRef:
            name: order-secret
        env:
        - name: SOCKET_IO_URL
          value: "http://socketio:3300"