apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-food
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-food
  template:
    metadata:
      labels:
        app: order-food
    spec:
      containers:
      - name: order-food
        image: asia-southeast1-docker.pkg.dev/findmyfood-455107/my-repo/order-food:latest
        ports:
        - containerPort: 8090
