apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: asia-southeast1-docker.pkg.dev/findmyfood-455107/my-repo/payment:latest
        ports:
        - containerPort: 5002
        envFrom:
        - secretRef:
            name: payment-secret
