apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672 # AMQP port
        - containerPort: 15672 # Management UI port
        volumeMounts:
        - name: config-volume
          mountPath: /etc/rabbitmq
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: config-volume
        configMap:
          name: rabbitmq-config
      - name: rabbitmq-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pvc