apiVersion: apps/v1
kind: Deployment
metadata:
  name: reccomendation
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reccomendation
  template:
    metadata:
      labels:
        app: reccomendation
    spec:
      containers:
      - name: reccomendation
        image: asia-southeast1-docker.pkg.dev/findmyfood-455107/my-repo/reccomendation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: reccomendation-secret
