apiVersion: apps/v1
kind: Deployment
metadata:
  name: reccomend-food
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reccomend-food
  template:
    metadata:
      labels:
        app: reccomend-food
    spec:
      containers:
      - name: reccomend-food
        image: asia-southeast1-docker.pkg.dev/findmyfood-455107/my-repo/reccomend-food:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
