apiVersion: apps/v1
kind: Deployment
metadata:
  name: reccomendation
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reccomendation
  template:
    metadata:
      labels:
        app: reccomendation
    spec:
      containers:
      - name: reccomendation
        image: ghcr.io/thykp/esd_team8-reccomendation:latest
        ports:
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: reccomendation-secret
