apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socketio
  template:
    metadata:
      labels:
        app: socketio
    spec:
      containers:
      - name: socketio
        image: ghcr.io/thykp/esd_team8-socket.io:latest
        ports:
        - containerPort: 3300
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: KONG_URL
          value: "http://kong:8000"
