apiVersion: v1
kind: Service
metadata:
  name: chatgpt
  namespace: esd
spec:
  type: NodePort
  selector:
    app: chatgpt
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300 # Fixed NodePort between 30000-32767
