apiVersion: v1
kind: Service
metadata:
  name: complete-order
  namespace: esd
spec:
  type: NodePort
  selector:
    app: complete-order
  ports:
  - port: 7070
    targetPort: 7070
    nodePort: 30770 # Fixed NodePort between 30000-32767
