apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: esd
spec:
  type: NodePort
  selector:
    app: kong
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
    nodePort: 30080 # Fixed NodePort between 30000-32767
  - name: proxy-ssl
    port: 8443
    targetPort: 8443
    nodePort: 30443 # Fixed NodePort between 30000-32767
  - name: admin
    port: 8001
    targetPort: 8001
    nodePort: 30081 # Fixed NodePort between 30000-32767
  - name: admin-ssl
    port: 8444
    targetPort: 8444
    nodePort: 30444 # Fixed NodePort between 30000-32767
  - name: gui
    port: 8002
    targetPort: 8002
    nodePort: 30082 # Fixed NodePort between 30000-32767
  - name: gui-ssl
    port: 8445
    targetPort: 8445
    nodePort: 30445 # Fixed NodePort between 30000-32767
  - name: extra1
    port: 8003
    targetPort: 8003
    nodePort: 30083 # Fixed NodePort between 30000-32767
  - name: extra2
    port: 8004
    targetPort: 8004
    nodePort: 30084 # Fixed NodePort between 30000-32767
