apiVersion: v1
kind: Service
metadata:
  name: menu
  namespace: esd
spec:
  type: NodePort
  selector:
    app: menu
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30501 # Fixed NodePort between 30000-32767
