apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: esd
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - port: 6369
    targetPort: 6369
    nodePort: 30369 # Fixed NodePort between 30000-32767