apiVersion: v1
kind: Service
metadata:
  name: order-food
  namespace: esd
spec:
  type: NodePort
  selector:
    app: order-food
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30809 # Fixed NodePort between 30000-32767
