apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: esd
spec:
  type: NodePort
  selector:
    app: payment
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30502 # Fixed NodePort between 30000-32767
