apiVersion: v1
kind: Service
metadata:
  name: queue
  namespace: esd
spec:
  type: NodePort
  selector:
    app: queue
  ports:
  - port: 8008
    targetPort: 8008
    nodePort: 30088 # Fixed NodePort between 30000-32767
