apiVersion: v1
kind: Service
metadata:
  name: reccomend-food
  namespace: esd
spec:
  type: NodePort
  selector:
    app: reccomend-food
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30808 # Fixed NodePort between 30000-32767
