apiVersion: v1
kind: Service
metadata:
  name: reccomendation
  namespace: esd
spec:
  type: NodePort
  selector:
    app: reccomendation
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30400 # Fixed NodePort between 30000-32767
