apiVersion: v1
kind: Service
metadata:
  name: socketio
  namespace: esd
spec:
  type: NodePort
  selector:
    app: socketio
  ports:
  - port: 3300
    targetPort: 3300
    nodePort: 30330 # Fixed NodePort between 30000-32767
