apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: esd
type: Opaque
data:
  # idk how you masked it so just leaving it here
  SUPABASE_URL: "aHR0cHM6Ly9hd21zZG1iemNqY2dueHFyY3pmYi5zdXBhYmFzZS5jbw=="
  SUPABASE_KEY: "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1GM2JYTmtiV0o2WTJwaloyNTRjWEpqZW1aaUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTkRJek5qRTJNek1zSW1WNGNDSTZNakExTnprek56WXpNMzAuNkR0VGpaNkFpQnpSblo5dnY3RnZuMkhzQVBqOFBmS2dGWlc4V2lJRGZLVQ=="