apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: esd
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kong'
        static_configs:
          - targets: ['kong-dbless:8001']
