apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: esd
data:
  rabbitmq.conf: |
    default_user = guest
    default_pass = guest
    loopback_users.guest = false
  enabled_plugins: |
    [rabbitmq_management].