apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: findmyfood
  namespace: esd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Thykp/ESD_Team8'
    targetRevision: HEAD
    path: backend/kubernetes
  destination: # where the application is gonna be deployed
    server: 'https://kubernetes.default.svc' # default here is the api server url ie WHERE the cluster is deployed under
    namespace: esd #you want to deploy your application in the esd namespace of the cluster => namespace is your logical PARTITION within that cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
