apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: findmyfood
  namespace: esd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Thykp/ESD_Team8'
    targetRevision: HEAD
    path: backend/kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
