apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-setup
  namespace: esd
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo "Waiting for RabbitMQ..."; sleep 2; done']
      containers:
      - name: rabbitmq-setup
        image: ghcr.io/thykp/esd_team8-rabbitmq:latest
        command: ["python3", "/app/amqp_setup.py"]
      restartPolicy: OnFailure
