apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-setup
  namespace: esd
spec:
  template:
    spec:
      containers:
      - name: rabbitmq-setup
        image: curlimages/curl
        command:
        - /bin/sh
        - -c
        - |
          curl -u guest:guest -X PUT http://rabbitmq:15672/api/exchanges/%2F/main -H "Content-Type: application/json" -d '{"type":"topic","durable":true}'
          curl -u guest:guest -X PUT http://rabbitmq:15672/api/queues/%2F/notifications -H "Content-Type: application/json" -d '{"durable":true}'
          curl -u guest:guest -X POST http://rabbitmq:15672/api/bindings/%2F/e/main/q/notifications -H "Content-Type: application/json" -d '{"routing_key":"#.notifications"}'
      restartPolicy: Never
  backoffLimit: 4