apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-setup
  namespace: esd
spec:
  template:
    spec:
      containers:
      - name: rabbitmq-setup
        image: ghcr.io/thykp/esd_team8-rabbitmq:latest
        # If needed, add command/args here
      restartPolicy: OnFailure
