name: Build and Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push images
        run: |
          for dir in ./services/simple/* ./services/complex/* ./socket.io ./rabbitmq; do
            if [ -f "$dir/Dockerfile" ]; then
              service=$(basename "$dir")
              echo "📦 Building and pushing $service"
              docker build -t ghcr.io/${{ github.repository_owner }}/$service:latest $dir
              docker push ghcr.io/${{ github.repository_owner }}/$service:latest
            fi
          done
