name: ArgoCD Sync

on:
  push:
    branches:
      - main
    paths:
      - 'backend/kubernetes/**'
      - '.github/workflows/argocd-sync.yml'
      
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Retrieve Argo CD Password
        id: argocd_password
        run: |
          ARGOCD_PASSWORD=$(kubectl get secret argocd-initial-admin-secret -n esd -o jsonpath="{.data.password}" | base64 -d)
          echo "ARGOCD_PASSWORD=$ARGOCD_PASSWORD" >> $GITHUB_ENV

      - name: Login to Argo CD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: admin
        run: |
          argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password ${{ env.ARGOCD_PASSWORD }} --insecure

      - name: Sync Application
        run: |
          argocd app sync findmyfood