name: Build and Push to GHCR

on:
  push:
    branches: [main] # Only triggers on pushes to the main branch
    paths:
      - 'backend/services/simple/**'
      - 'backend/services/complex/**'
      - 'socket.io/**'
      - 'rabbitmq/Dockerfile'
      - '.github/workflows/docker-build-push.yml'
      
  workflow_dispatch: # Allows manual triggering
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Images
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.repository }}" | awk -F/ '{print $2}' | tr '[:upper:]' '[:lower:]')

          for dir in backend/services/simple/* backend/services/complex/* backend/socket.io backend/rabbitmq; do
            if [ -f "$dir/Dockerfile" ]; then
              service=$(basename "$dir")
              image="ghcr.io/$OWNER/${REPO}-$service:latest"
              echo "📦 Building $service"
              docker build -t "$image" "$dir"
              echo "🚀 Pushing $image"
              docker push "$image"
              echo "✅ Done with $service"
              echo "---------------------------"
            fi
          done
